import type { Config } from 'tailwindcss';
const colors = require('tailwindcss/colors');

export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    colors: {
      white: 'var(--color-white)',
      black: 'var(--color-black)',
      surface: {
        1: 'var(--color-surface-1)',
        2: 'var(--color-surface-2)',
        3: 'var(--color-surface-3)',
        4: 'var(--color-surface-4)',
        5: 'var(--color-surface-5)',
        6: 'var(--color-surface-6)',
        7: 'var(--color-surface-7)',
        8: 'var(--color-surface-8)',
        9: 'var(--color-surface-9)',
        10: 'var(--color-surface-10)',
        11: 'var(--color-surface-11)',
        12: 'var(--color-surface-12)',
      },
      surfaceA: {
        1: 'var(--color-surfaceA-1)',
        2: 'var(--color-surfaceA-2)',
        3: 'var(--color-surfaceA-3)',
        4: 'var(--color-surfaceA-4)',
        5: 'var(--color-surfaceA-5)',
        6: 'var(--color-surfaceA-6)',
        7: 'var(--color-surfaceA-7)',
        8: 'var(--color-surfaceA-8)',
        9: 'var(--color-surfaceA-9)',
        10: 'var(--color-surfaceA-10)',
        11: 'var(--color-surfaceA-11)',
        12: 'var(--color-surfaceA-12)',
      },
      primary: {
        1: 'var(--color-primary-1)',
        2: 'var(--color-primary-2)',
        3: 'var(--color-primary-3)',
        4: 'var(--color-primary-4)',
        5: 'var(--color-primary-5)',
        6: 'var(--color-primary-6)',
        7: 'var(--color-primary-7)',
        8: 'var(--color-primary-8)',
        9: 'var(--color-primary-9)',
        10: 'var(--color-primary-10)',
        11: 'var(--color-primary-11)',
        12: 'var(--color-primary-12)',
      },
      primaryA: {
        1: 'var(--color-primaryA-1)',
        2: 'var(--color-primaryA-2)',
        3: 'var(--color-primaryA-3)',
        4: 'var(--color-primaryA-4)',
        5: 'var(--color-primaryA-5)',
        6: 'var(--color-primaryA-6)',
        7: 'var(--color-primaryA-7)',
        8: 'var(--color-primaryA-8)',
        9: 'var(--color-primaryA-9)',
        10: 'var(--color-primaryA-10)',
        11: 'var(--color-primaryA-11)',
        12: 'var(--color-primaryA-12)',
      },
      secondary: {
        1: 'var(--color-secondary-1)',
        2: 'var(--color-secondary-2)',
        3: 'var(--color-secondary-3)',
        4: 'var(--color-secondary-4)',
        5: 'var(--color-secondary-5)',
        6: 'var(--color-secondary-6)',
        7: 'var(--color-secondary-7)',
        8: 'var(--color-secondary-8)',
        9: 'var(--color-secondary-9)',
        10: 'var(--color-secondary-10)',
        11: 'var(--color-secondary-11)',
        12: 'var(--color-secondary-12)',
      },
      secondaryA: {
        1: 'var(--color-token-eggplantA-1)',
        2: 'var(--color-token-eggplantA-2)',
        3: 'var(--color-token-eggplantA-3)',
        4: 'var(--color-token-eggplantA-4)',
        5: 'var(--color-token-eggplantA-5)',
        6: 'var(--color-token-eggplantA-6)',
        7: 'var(--color-token-eggplantA-7)',
        8: 'var(--color-token-eggplantA-8)',
        9: 'var(--color-token-eggplantA-9)',
        10: 'var(--color-token-eggplantA-10)',
        11: 'var(--color-token-eggplantA-11)',
        12: 'var(--color-token-eggplantA-12)',
      },
      disabled: {
        1: 'var(--color-disabled-1)',
        2: 'var(--color-disabled-2)',
        3: 'var(--color-disabled-3)',
        4: 'var(--color-disabled-4)',
        5: 'var(--color-disabled-5)',
        6: 'var(--color-disabled-6)',
        7: 'var(--color-disabled-7)',
        8: 'var(--color-disabled-8)',
        9: 'var(--color-disabled-9)',
        10: 'var(--color-disabled-10)',
        11: 'var(--color-disabled-11)',
        12: 'var(--color-disabled-12)',
      },
      disabledA: {
        1: 'var(--color-disabledA-1)',
        2: 'var(--color-disabledA-2)',
        3: 'var(--color-disabledA-3)',
        4: 'var(--color-disabledA-4)',
        5: 'var(--color-disabledA-5)',
        6: 'var(--color-disabledA-6)',
        7: 'var(--color-disabledA-7)',
        8: 'var(--color-disabledA-8)',
        9: 'var(--color-disabledA-9)',
        10: 'var(--color-disabledA-10)',
        11: 'var(--color-disabledA-11)',
        12: 'var(--color-disabledA-12)',
      },
      warning: {
        1: 'var(--color-warning-1)',
        2: 'var(--color-warning-2)',
        3: 'var(--color-warning-3)',
        4: 'var(--color-warning-4)',
        5: 'var(--color-warning-5)',
        6: 'var(--color-warning-6)',
        7: 'var(--color-warning-7)',
        8: 'var(--color-warning-8)',
        9: 'var(--color-warning-9)',
        10: 'var(--color-warning-10)',
        11: 'var(--color-warning-11)',
        12: 'var(--color-warning-12)',
      },
      warningA: {
        1: 'var(--color-warningA-1)',
        2: 'var(--color-warningA-2)',
        3: 'var(--color-warningA-3)',
        4: 'var(--color-warningA-4)',
        5: 'var(--color-warningA-5)',
        6: 'var(--color-warningA-6)',
        7: 'var(--color-warningA-7)',
        8: 'var(--color-warningA-8)',
        9: 'var(--color-warningA-9)',
        10: 'var(--color-warningA-10)',
        11: 'var(--color-warningA-11)',
        12: 'var(--color-warningA-12)',
      },
      error: {
        1: 'var(--color-error-1)',
        2: 'var(--color-error-2)',
        3: 'var(--color-error-3)',
        4: 'var(--color-error-4)',
        5: 'var(--color-error-5)',
        6: 'var(--color-error-6)',
        7: 'var(--color-error-7)',
        8: 'var(--color-error-8)',
        9: 'var(--color-error-9)',
        10: 'var(--color-error-10)',
        11: 'var(--color-error-11)',
        12: 'var(--color-error-12)',
      },
      errorA: {
        1: 'var(--color-errorA-1)',
        2: 'var(--color-errorA-2)',
        3: 'var(--color-errorA-3)',
        4: 'var(--color-errorA-4)',
        5: 'var(--color-errorA-5)',
        6: 'var(--color-errorA-6)',
        7: 'var(--color-errorA-7)',
        8: 'var(--color-errorA-8)',
        9: 'var(--color-errorA-9)',
        10: 'var(--color-errorA-10)',
        11: 'var(--color-errorA-11)',
        12: 'var(--color-errorA-12)',
      },
      success: {
        1: 'var(--color-success-1)',
        2: 'var(--color-success-2)',
        3: 'var(--color-success-3)',
        4: 'var(--color-success-4)',
        5: 'var(--color-success-5)',
        6: 'var(--color-success-6)',
        7: 'var(--color-success-7)',
        8: 'var(--color-success-8)',
        9: 'var(--color-success-9)',
        10: 'var(--color-success-10)',
        11: 'var(--color-success-11)',
        12: 'var(--color-success-12)',
      },
      successA: {
        1: 'var(--color-successA-1)',
        2: 'var(--color-successA-2)',
        3: 'var(--color-successA-3)',
        4: 'var(--color-successA-4)',
        5: 'var(--color-successA-5)',
        6: 'var(--color-successA-6)',
        7: 'var(--color-successA-7)',
        8: 'var(--color-successA-8)',
        9: 'var(--color-successA-9)',
        10: 'var(--color-successA-10)',
        11: 'var(--color-successA-11)',
        12: 'var(--color-successA-12)',
      },
      'page-background': 'var(--color-page-background)',
      text: {
        muted: 'var(--color-text-muted)',
        subtle: 'var(--color-text-subtle)',
        base: 'var(--color-text-base)',
      },
      icon: {
        muted: 'var(--color-icon-muted)',
        base: 'var(--color-icon-base)',
      },
      border: {
        muted: 'var(--color-border-muted)',
        base: 'var(--color-border-base)',
        bright: 'var(--color-border-bright)',
      },
      transparent: colors.transparent,
    },
    extend: {
      fontFamily: {
        inter: ['Inter', 'monospace'],
        'plex-mono': ['IBM Plex Mono', 'monospace'],
      },
      screens: {
        '3xl': '1600px',
      },
    },
  },
} satisfies Config;
