export const opaque = [
  "Diffusers Model Loader",
  "Diffusers Hub Model Down-Loader",
  "CLIPSeg Model Loader",
  "Cache Node",
  "Load Cache",
  "Export API",
  "CR Load Text List",
  "CR Save Text To File",
  "CR Output Schedule To File",
  "CR Font File List",
  "CR Load Schedule From File",
  "Load Text File",
  "Save Text File",
  "Create Morph Image",
  "Write to GIF",
  "Write to Video",
  "Video Dump Frames",
  "Create Video from Path",
  "Create Morph Image from Path",
  "CR Output Flow Frames",
  "CR XY Save Grid Image",
  "Log File [Dream]",
  "CSV Generator [Dream]",
  "CSV Curve [Dream]",
  "Image Sequence Saver [Dream]",
  "CreateTextMask",
  "CreateAudioMask",
  "SoundReactive",
  "Checkpoint",
  "Lora",
  "Export With Ffmpeg (mtb)",
  "Add To Playlist (mtb)",
  "Read Playlist (mtb)",
  "Face Swap (mtb)",
  "Load Face Swap Model (mtb)",
  "Load Face Analysis Model (mtb)",
  "Curve (mtb)",
  "Save Tensors (mtb)",
  "Load Image Sequence (mtb)",
  "Save Image Sequence (mtb)",
  "Load Image From Url (mtb)",
  "Save Image Grid (mtb)",
  "Save Gif (mtb)",
  "ttN imageOutput",
  "Create QR Code",
  "Qr Code (mtb)",
  "0246.Highway",
  "0246.HighwayBatch",
  "0246.Cloud",
  "Save Prompt (WLSH)",
  "Save Prompt/Info (WLSH)",
  "Save Positive Prompt(WLSH)",
];
